name: Cache Test Workflow

on:
  push:
    branches:
      - main  # or master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js (example dependency)
        uses: actions/setup-node@v3
        with:
          node-version: "20"

      - name: Cache dependencies
        id: cache-step
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: cache-3b78282
          restore-keys: |
            cache-3b78282

      - name: prime-cache-3b78282
        run: |
          if [ -n "${{ steps.cache-step.outputs.cache-hit }}" ]; then
            echo "Cache hit: ${{ steps.cache-step.outputs.cache-hit }}"
          else
            echo "Cache miss"
          fi
