name: Email Step Test

on:
  push:
    branches:
      - main  # or master

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: 24f1002686@ds.study.iitm.ac.in
        run: echo "Hello, world!"
